### ISSUE TITLE
[RE-Front-task] 카카오맵 API 재구현

### ISSUE THREAD

**Issue by D-MG-lab** [codestates/brewhere#133]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 카카오맵 API 재 구현

### TODO
1. [ ] react-kakao-maps-sdk로 재구현
2. [ ] Info 아이콘 사이즈 조정
3. [ ] 카카오맵 중첩 오류 해결
4. [ ] 인포윈도우 디자인 바꾸기 (or 구현 방식 변경)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
