### ISSUE TITLE
[RE-back - task] 사용자 CRUD 재구현

### ISSUE THREAD

**Issue by hsly22xk** [codestates/brewhere#140]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 사용자 CRUD 기능 리팩토링

### TODO
1. [x] 회원가입, 로그인, 로그아웃 기능 재구현
2. [x] 로컬 환경에서 구현되는지 확인하기
3. [x] 데이터베이스 users 테이블 재구성

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Low`
