### ISSUE TITLE
[back - Task] sequelize와 router 분기 코드 작성

### ISSUE THREAD

**Issue by hsly22xk** [codestates/brewhere#40]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 

### TODO
1. [x] sequelize를 활용한 데이터 테이블 생성
2. [x] 라우터를 만들어 분기점 나누기
3. [x] 라우터에 따른 컨트롤러 나누기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
