### ISSUE TITLE
[Front-task] 내비게이션 바 만들기

### ISSUE THREAD

**Issue by kitch-finn** [codestates/brewhere#49]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 화면 상단에 고정될 내비바 만들기

### TODO
1. [x] 로고를 누르면 홈으로 이동
2. [x] 로그인 누르면 로그인 모달 창 활성화
3. [ ] 로그인 상태일 시 로그아웃으로 표기
4. [x] 메뉴창 만들기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
