### ISSUE TITLE
[Front-task] Map 페이지 만들기

### ISSUE THREAD

**Issue by kitch-finn** [codestates/brewhere#50]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 프로토타입을 토대로 Map 페이지 만들기

### TODO
1. [x] 카카오맵 API로 맵 구현
2. [ ] 지도 API를 활용해 서울-브루어리로 검색된 상태의 지도 집어넣기 
3. [ ] 선택된 가게의 핀 클릭시 가게 상세정보 모달창 띄우기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
